export const DEV_ENV = typeof google === 'undefined'
export const DEFAULT_MOCK_API_DELAY = 3000
export const STATUSES = [
  'New Request',
  'Accepted',
  'In Progress',
  'For Review by BW',
  'Approved by BW',
  'Rework',
  'S&S',
  'Delivered',
  'Archived',
]
export const BLANK_FORM_DATA = {
  projectId: '',
  status: '',
  clientName: '',
  projectName: '',
  siteAddress: '',
  city: '',
  state: '',
  country: '',
  zip: '',
  opbSize: '',
  opbPostSpacing: '',
  opbPostSize: '',
  opbMainBldGpitch: '',
  opbMetalRoofPanelGauge: '',
  opbConnectSlab: '',
  epbSize: '',
  epbPostSpacing: '',
  epbPostSize: '',
  epbMainBldGpitch: '',
  epbMetalRoofPanelGauge: '',
  epbConnectSlab: '',
  pepbSize: '',
  pepbPostSpacing: '',
  pepbPostSize: '',
  pepbMainBldGpitch: '',
  pepbMetalRoofPanelGauge: '',
  pepbConnectSlab: '',
  trussSize: '',
  trussPostSpacing: '',
  trussPostSize: '',
  trussMainBldGpitch: '',
  trussMetalRoofPanelGauge: '',
  trussConnectSlab: '',
  overhangType: '',
  overhangValue: '',
  riskCategory: '',
  exposureCategory: '',
  plywoodOnSiding: '',
  plywoodOnRoof: '',
  windSpeed: '',
  wetMapAndSeal: false,
  studSpacing: '',
  studSpacingCustomValue: '',
  price: '',
  // Add-Ons
  addOnDoorSelected: false,
  addOnDoorEpbQty: '',
  addOnDoorEpbSize: '',
  addOnDoorPepbQty: '',
  addOnDoorPepbSize: '',
  addOnWindowSelected: false,
  addOnWindowEpbQty: '',
  addOnWindowEpbSize: '',
  addOnWindowPepbQty: '',
  addOnWindowPepbSize: '',
  addOnLeanToSelected: false,
  addOnLeanToOpbSize: '',
  addOnLeanToOpbPitch: '',
  addOnLeanToOpbSlab: '',
  addOnLeanToOpbPostSize: '',
  addOnLeanToEpbSize: '',
  addOnLeanToEpbPitch: '',
  addOnLeanToEpbSlab: '',
  addOnLeanToEpbPostSize: '',
  addOnLeanToPepbSize: '',
  addOnLeanToPepbPitch: '',
  addOnLeanToPepbSlab: '',
  addOnLeanToPepbPostSize: '',
  orderedBy: '',
  signature: '',
  orderDate: '',
  additionalInformation: '',
  driveFolder: '',
}
