export const DEV_ENV = typeof google === 'undefined'
export const DEFAULT_MOCK_API_DELAY = 1000
export const STATUSES = [
  'New Request',
  'Accepted',
  'In Progress',
  'For Review by BW',
  'Approved by BW',
  'Rework',
  'S&S',
  'Delivered',
  'Archived',
]

export const STATES = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'DC',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
]
export const BLANK_FORM_DATA = {
  projectId: '',
  status: 'New Request',
  clientName: '',
  projectName: '',
  siteAddress: '',
  city: '',
  state: '',
  country: '',
  zip: '',
  projectType: '',
  opbSize: '',
  opbPostSpacing: '',
  opbPostSize: '',
  opbMainBldgPitch: '',
  opbMetalRoofPanelGauge: '',
  opbConnectSlab: '',
  epbSize: '',
  epbPostSpacing: '',
  epbPostSize: '',
  epbMainBldgPitch: '',
  epbMetalRoofPanelGauge: '',
  epbConnectSlab: '',
  pepbSize: '',
  pepbPostSpacing: '',
  pepbPostSize: '',
  pepbMainBldgPitch: '',
  pepbMetalRoofPanelGauge: '',
  pepbConnectSlab: '',
  trussSize: '',
  trussPostSpacing: '',
  trussPostSize: '',
  trussMainBldgPitch: '',
  trussMetalRoofPanelGauge: '',
  trussConnectSlab: '',
  overhangType: '',
  overhangValue: '',
  riskCategory: '',
  exposureCategory: '',
  plywoodOnSiding: '',
  plywoodOnRoof: '',
  windSpeed: '145MPH',
  wetMapAndSeal: false,
  studSpacing: '',
  studSpacingCustomValue: '',
  price: '',
  // Add-Ons
  addOnDoorSelected: false,
  addOnDoorEpbQty: '',
  addOnDoorEpbSize: '',
  addOnDoorPepbQty: '',
  addOnDoorPepbSize: '',
  addOnWindowSelected: false,
  addOnWindowEpbQty: '',
  addOnWindowEpbSize: '',
  addOnWindowPepbQty: '',
  addOnWindowPepbSize: '',
  addOnLeanToSelected: false,
  addOnLeanToOpbSize: '',
  addOnLeanToOpbPitch: '',
  addOnLeanToOpbSlab: '',
  addOnLeanToOpbPostSize: '',
  addOnLeanToEpbSize: '',
  addOnLeanToEpbPitch: '',
  addOnLeanToEpbSlab: '',
  addOnLeanToEpbPostSize: '',
  addOnLeanToPepbSize: '',
  addOnLeanToPepbPitch: '',
  addOnLeanToPepbSlab: '',
  addOnLeanToPepbPostSize: '',
  orderedBy: '',
  signature: '',
  orderDate: new Date().toISOString().split('T')[0],
  additionalInformation: '',
  driveFolder: '',
  opbPaperSold: '',
  leanToPaperSold: '',
  singleSlopePaperSold: '',
}

export const PAPER_COPY_TYPES = {
  openPoleBarn: 'Open Pole Barn',
  leanTo: 'Lean To',
  singleSlope: 'Single Slope',
}

export const PAPER_COPY_ICONS = {
  openPoleBarn: 'mdi-home-variant',
  leanTo: 'mdi-home-roof',
  singleSlope: 'mdi-home-city',
}

export const PAPER_COPY_THRESHOLDS = {
  lowStock: 3,
  warningStock: 5,
  goodStock: 10,
}

export const PAPER_COPY_STOCK_COLORS = {
  lowStock: 'error',
  warningStock: 'warning',
  goodStock: 'success',
}

export const PAPER_COPY_CARD_CSS_CLASSES = {
  lowStock: 'low-stock-card',
  warningStock: 'warning-stock-card',
  goodStock: 'good-stock-card',
}

export const GET_STOCK_LEVEL_KEY = (stock) => {
  stock = stock || 0
  return stock <= PAPER_COPY_THRESHOLDS.lowStock
    ? 'lowStock'
    : stock <= PAPER_COPY_THRESHOLDS.warningStock
      ? 'warningStock'
      : 'goodStock'
}
