function testUpdateProject() {
  let data = {
    country: 'India',
    pepbPostSpacing: '',
    projectName: 'Test',
    signature: 'JESSIE CHANEY',
    studSpacing: '24',
    opbMetalRoofPanelGauge: '12',
    trussMainBldgPitch: '',
    addOnDoorSelected: false,
    epbSize: '',
    addOnWindowSelected: false,
    plywoodOnSiding: 'No',
    wetMapAndSeal: true,
    addOnWindowEpbSize: '',
    siteAddress: '28, First Floor, First Cross',
    driveFolder: 'https://drive.google.com/drive/folders/1hmIUY0zF8cw-a7keikY-57siWACYRfpC',
    pepbMainBldgPitch: '',
    overhangType: '',
    addOnLeanToOpbPostSize: '',
    riskCategory: '3',
    existingImages: [
      {
        id: 1755615762507.8447,
        name: 'Brands.txt',
        url: 'https://drive.google.com/file/d/1KGAKv-QVzcZIPXr1X4gEZERiqpGr6AL7/view?usp=drivesdk',
      },
    ],
    zip: '560077',
    orderDate: '2025-08-21',
    addOnDoorEpbQty: '',
    opbMainBldgPitch: '4/12',
    addOnLeanToPepbPitch: '',
    pepbSize: '',
    additionalInformation: 'safdsfd',
    addOnDoorPepbQty: '',
    epbConnectSlab: '',
    addOnLeanToOpbPitch: '',
    sketchData: [],
    projectId: '999.18',
    addOnLeanToEpbPitch: '',
    addOnDoorEpbSize: '',
    addOnLeanToPepbPostSize: '',
    studSpacingCustomValue: '',
    addOnLeanToEpbSlab: '',
    epbPostSpacing: '',
    trussPostSpacing: '',
    opbPostSpacing: "12'",
    status: 'Rework',
    addOnWindowPepbQty: '',
    addOnWindowEpbQty: '',
    epbMetalRoofPanelGauge: '',
    addOnLeanToPepbSlab: '',
    orderedBy: 'JESSIE CHANEY',
    plywoodOnRoof: 'Yes',
    pepbPostSize: '',
    overhangValue: '',
    windSpeed: '145 MPH',
    addOnLeanToOpbSize: '',
    city: 'Bengaluru',
    addOnLeanToEpbPostSize: '',
    clientName: 'test test',
    trussMetalRoofPanelGauge: '',
    addOnLeanToSelected: false,
    addOnLeanToEpbSize: '',
    epbPostSize: '',
    addOnLeanToOpbSlab: '',
    trussPostSize: '',
    addOnWindowPepbSize: '',
    opbConnectSlab: '12',
    addOnDoorPepbSize: '',
    opbPostSize: '12x12',
    opbSize: '12x12x12',
    trussConnectSlab: '',
    pepbConnectSlab: '',
    price: '1',
    trussSize: '',
    pepbMetalRoofPanelGauge: '',
    state: 'Florida',
    epbMainBldgPitch: '',
    addOnLeanToPepbSize: '',
    exposureCategory: 'B',
    projectType: 'typicalOpbOnly',
  }

  updateProject({ data, token: 'mdkbv1by.al' })
}

function testFieldChangeEmail() {
  let data = {
    addOnLeanToEpbPostSize: '',
    overhangValue: '',
    pepbPostSize: '',
    addOnLeanToOpbPitch: '',
    studSpacing: '16',
    epbSize: '',
    opbConnectSlab: 'OPTIONAL',
    addOnLeanToPepbPostSize: '',
    pepbConnectSlab: '',
    addOnWindowEpbSize: '',
    addOnLeanToEpbSlab: '',
    opbMetalRoofPanelGauge: '26',
    addOnLeanToPepbPitch: '',
    addOnWindowEpbQty: '',
    epbConnectSlab: '',
    wetMapAndSeal: false,
    addOnDoorPepbSize: '',
    addOnDoorPepbQty: '',
    addOnLeanToPepbSlab: '',
    trussConnectSlab: '',
    sketchData: [],
    trussMainBldgPitch: '',
    plywoodOnSiding: 'Yes',
    zip: '560077',
    addOnLeanToEpbPitch: '',
    trussPostSize: '',
    addOnWindowPepbQty: '',
    opbSize: '24x24x10',
    orderDate: '2025-08-04',
    driveFolder: '',
    studSpacingCustomValue: '',
    opbMainBldgPitch: '4/12',
    additionalInformation: 'Test',
    windSpeed: '150 MPH',
    epbMetalRoofPanelGauge: '',
    price: '1',
    epbPostSpacing: '',
    city: 'Bengaluru',
    addOnLeanToOpbPostSize: '',
    addOnWindowPepbSize: '',
    siteAddress: '28, First Floor, First Cross',
    projectName: 'Test',
    addOnWindowSelected: false,
    addOnLeanToPepbSize: '',
    addOnLeanToOpbSlab: '',
    country: 'India',
    orderedBy: 'Test',
    trussSize: '',
    trussMetalRoofPanelGauge: '',
    opbPostSpacing: "12'",
    riskCategory: '2',
    epbPostSize: '',
    trussPostSpacing: '',
    existingImages: [],
    addOnLeanToEpbSize: '',
    exposureCategory: 'B',
    signature: 'Test',
    addOnDoorEpbQty: '',
    status: 'New Request',
    overhangType: 'standard',
    addOnLeanToOpbSize: '',
    pepbMetalRoofPanelGauge: '',
    plywoodOnRoof: 'Yes',
    opbPostSize: '6x6',
    pepbSize: '',
    epbMainBldgPitch: '',
    projectId: '100.00',
    addOnLeanToSelected: false,
    addOnDoorSelected: false,
    state: 'FL',
    pepbMainBldgPitch: '',
    pepbPostSpacing: '',
    clientName: 'test test',
    addOnDoorEpbSize: '',
  }

  let newData = { ...data }
  newData.price = 2
  newData.projectName = 'Test 2'
  sendFieldChangeEmail(data, newData, { user: { name: 'Test User' } })
}

function testGgeneratePresentation() {
  let data = {
    addOnLeanToEpbPostSize: '',
    overhangValue: '',
    pepbPostSize: '',
    addOnLeanToOpbPitch: '',
    studSpacing: '16',
    epbSize: '',
    opbConnectSlab: 'OPTIONAL',
    addOnLeanToPepbPostSize: '',
    pepbConnectSlab: '',
    addOnWindowEpbSize: '',
    addOnLeanToEpbSlab: '',
    opbMetalRoofPanelGauge: '26',
    addOnLeanToPepbPitch: '',
    addOnWindowEpbQty: '',
    epbConnectSlab: '',
    wetMapAndSeal: false,
    addOnDoorPepbSize: '',
    addOnDoorPepbQty: '',
    addOnLeanToPepbSlab: '',
    trussConnectSlab: '',
    sketchData: [],
    trussMainBldgPitch: '',
    plywoodOnSiding: 'Yes',
    zip: '560077',
    addOnLeanToEpbPitch: '',
    trussPostSize: '',
    addOnWindowPepbQty: '',
    opbSize: '24x24x10',
    orderDate: '2025-08-04',
    driveFolder: '',
    studSpacingCustomValue: '',
    opbMainBldgPitch: '4/12',
    additionalInformation: 'Test',
    windSpeed: '150 MPH',
    epbMetalRoofPanelGauge: '',
    price: '1',
    epbPostSpacing: '',
    city: 'Bengaluru',
    addOnLeanToOpbPostSize: '',
    addOnWindowPepbSize: '',
    siteAddress: '28, First Floor, First Cross',
    projectName: 'Test',
    addOnWindowSelected: false,
    addOnLeanToPepbSize: '',
    addOnLeanToOpbSlab: '',
    country: 'India',
    orderedBy: 'Test',
    trussSize: '',
    trussMetalRoofPanelGauge: '',
    opbPostSpacing: "12'",
    riskCategory: '2',
    epbPostSize: '',
    trussPostSpacing: '',
    existingImages: [],
    addOnLeanToEpbSize: '',
    exposureCategory: 'B',
    signature: 'Test',
    addOnDoorEpbQty: '',
    status: 'New Request',
    overhangType: 'standard',
    addOnLeanToOpbSize: '',
    pepbMetalRoofPanelGauge: '',
    plywoodOnRoof: 'Yes',
    opbPostSize: '6x6',
    pepbSize: '',
    epbMainBldgPitch: '',
    projectId: '',
    addOnLeanToSelected: false,
    addOnDoorSelected: false,
    state: 'FL',
    pepbMainBldgPitch: '',
    pepbPostSpacing: '',
    clientName: 'test test',
    addOnDoorEpbSize: '',
  }

  PropertiesService.getScriptProperties().getProperty()
  let exportData = generatePresentation(data)
}

function testStatusChange() {
  let projectId = '450.461'
  let newStatus = 'Rework'
  updateProjectStatus({ data: { projectId, newStatus } })
}

function testSendStatusChangeEmail() {
  let projectId = '450.461'
  let oldStatus = 'Rework'
  let newStatus = 'Approved by BW'
  let projectData = getDataByProjectName_(projectId)
  sendStatusChangeEmail(oldStatus, newStatus, projectData.data)
}

function testPresentationEmail() {
  createDelayedPresentationEmailTrigger({
    data: {
      country: 'India',
      pepbPostSpacing: '',
      projectName: 'Test',
      signature: 'JESSIE CHANEY',
      studSpacing: '24',
      opbMetalRoofPanelGauge: '12',
      trussMainBldgPitch: '',
      addOnDoorSelected: false,
      projectType: 'typicalOpbOnly',
      epbSize: '',
      addOnWindowSelected: false,
      plywoodOnSiding: 'No',
      wetMapAndSeal: true,
      addOnWindowEpbSize: '',
      siteAddress: '28, First Floor, First Cross',
      driveFolder: 'https://drive.google.com/drive/folders/1MXyqwCBhYFK0jVdkMpusUxkkXkpzJ70l',
      pepbMainBldgPitch: '',
      overhangType: '',
      addOnLeanToOpbPostSize: '',
      riskCategory: '3',
      existingImages: [
        {
          id: 1755615762507.8447,
          name: 'Brands.txt',
          url: 'https://drive.google.com/file/d/1KGAKv-QVzcZIPXr1X4gEZERiqpGr6AL7/view?usp=drivesdk',
        },
      ],
      zip: '560077',
      orderDate: '2025-08-21',
      addOnDoorEpbQty: '',
      opbMainBldgPitch: '4/12',
      addOnLeanToPepbPitch: '',
      pepbSize: '',
      additionalInformation: 'safdsfd',
      addOnDoorPepbQty: '',
      epbConnectSlab: '',
      addOnLeanToOpbPitch: '',
      projectId: '999.23',
      addOnLeanToEpbPitch: '',
      addOnDoorEpbSize: '',
      addOnLeanToPepbPostSize: '',
      studSpacingCustomValue: '',
      addOnLeanToEpbSlab: '',
      epbPostSpacing: '',
      trussPostSpacing: '',
      opbPostSpacing: "12'",
      status: 'Rework',
      addOnWindowPepbQty: '',
      addOnWindowEpbQty: '',
      epbMetalRoofPanelGauge: '',
      addOnLeanToPepbSlab: '',
      orderedBy: 'JESSIE CHANEY',
      plywoodOnRoof: 'Yes',
      pepbPostSize: '',
      overhangValue: '',
      windSpeed: '145 MPH',
      addOnLeanToOpbSize: '',
      city: 'Bengaluru',
      addOnLeanToEpbPostSize: '',
      clientName: 'test test',
      trussMetalRoofPanelGauge: '',
      addOnLeanToSelected: false,
      addOnLeanToEpbSize: '',
      epbPostSize: '',
      addOnLeanToOpbSlab: '',
      trussPostSize: '',
      addOnWindowPepbSize: '',
      opbConnectSlab: '12',
      addOnDoorPepbSize: '',
      opbPostSize: '12x12',
      opbSize: '12x12x12',
      trussConnectSlab: '',
      pepbConnectSlab: '',
      price: '1',
      trussSize: '',
      pepbMetalRoofPanelGauge: '',
      state: 'Florida',
      epbMainBldgPitch: '',
      addOnLeanToPepbSize: '',
      exposureCategory: 'B',
      fullAddress: '28, First Floor, First Cross, Bengaluru, Florida, India, 560077',
      buildingType: 'Open Pole Barn',
      presentationUrl:
        'https://drive.google.com/file/d/1iBccgDu3eCtcADanseHu3_J-ChooD37v/view?usp=drivesdk',
    },
    pdfUrl: 'https://drive.google.com/file/d/1iBccgDu3eCtcADanseHu3_J-ChooD37v/view?usp=drivesdk',
    slideUrl: 'https://docs.google.com/open?id=1uj1HvSX-VX1HFrY1qVvECqenmZzn9hIo9ysXum-1_pQ',
    errors: [],
    triggerId: '954954836834452111',
    createdAt: '2025-08-19T15:53:54.844Z',
  })
  let trigger = {
    second: 14,
    minute: 54,
    hour: 17,
    timezone: 'UTC',
    month: 8,
    year: 2025,
    'week-of-year': 34,
    triggerUid: '954954836834452111',
  }

  executeDelayedPresentationEmail(trigger)
}
